"""editable tin status and email open tracking

Revision ID: e8fd48028372
Revises: eb07c9c490e5
Create Date: 2026-07-06 21:50:01.990514
"""
from alembic import op
import sqlalchemy as sa


revision = 'e8fd48028372'
down_revision = 'eb07c9c490e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('tds_certificates', sa.Column(
        'has_12_digit_tin', sa.Boolean(), nullable=False, server_default=sa.false()))
    # Backfill existing certificates from their TIN length instead of
    # defaulting everyone to "No".
    op.execute("UPDATE tds_certificates SET has_12_digit_tin = (LENGTH(tin) = 12)")
    op.add_column('tds_dispatch_jobs', sa.Column('opened_at', sa.DateTime(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tds_dispatch_jobs', 'opened_at')
    op.drop_column('tds_certificates', 'has_12_digit_tin')
    # ### end Alembic commands ###
