"""initial tax certificate module schema

Revision ID: eb07c9c490e5
Revises: 
Create Date: 2026-07-05 00:29:26.820704
"""
from alembic import op
import sqlalchemy as sa


revision = 'eb07c9c490e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tds_import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('ok_rows', sa.Integer(), nullable=False),
    sa.Column('error_rows', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tds_number_sequences',
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('scope')
    )
    op.create_table('tds_numbering_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_token', sa.String(length=64), nullable=False),
    sa.Column('fiscal_year_format', sa.String(length=16), nullable=False),
    sa.Column('pad_width', sa.Integer(), nullable=False),
    sa.Column('start_number', sa.Integer(), nullable=False),
    sa.Column('reset_policy', sa.String(length=16), nullable=False),
    sa.Column('separator', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tds_org_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_address', sa.Text(), nullable=True),
    sa.Column('logo_path', sa.String(length=512), nullable=True),
    sa.Column('seal_signature_path', sa.String(length=512), nullable=True),
    sa.Column('officer_name', sa.String(length=255), nullable=True),
    sa.Column('officer_designation', sa.String(length=255), nullable=True),
    sa.Column('officer_email', sa.String(length=255), nullable=True),
    sa.Column('default_bank_name', sa.String(length=255), nullable=True),
    sa.Column('default_description', sa.String(length=255), nullable=True),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_user', sa.String(length=255), nullable=True),
    sa.Column('smtp_password', sa.String(length=255), nullable=True),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=False),
    sa.Column('smtp_from', sa.String(length=255), nullable=True),
    sa.Column('wa_provider', sa.String(length=20), nullable=True),
    sa.Column('wa_token', sa.String(length=512), nullable=True),
    sa.Column('wa_phone_number_id', sa.String(length=64), nullable=True),
    sa.Column('wa_twilio_sid', sa.String(length=64), nullable=True),
    sa.Column('wa_twilio_auth', sa.String(length=128), nullable=True),
    sa.Column('wa_twilio_from', sa.String(length=32), nullable=True),
    sa.Column('dispatch_mode', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tds_rate_anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=8), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tds_suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tin', sa.String(length=20), nullable=False),
    sa.Column('bin', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('party_type', sa.Enum('SUPPLIER', 'EMPLOYEE', 'OTHER', name='partytype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tds_suppliers_bin'), 'tds_suppliers', ['bin'], unique=False)
    op.create_index(op.f('ix_tds_suppliers_name'), 'tds_suppliers', ['name'], unique=False)
    op.create_index(op.f('ix_tds_suppliers_tin'), 'tds_suppliers', ['tin'], unique=True)
    op.create_table('tds_tax_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section', 'kind', 'effective_from')
    )
    op.create_index(op.f('ix_tds_tax_rates_section'), 'tds_tax_rates', ['section'], unique=False)
    op.create_table('tds_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_no', sa.String(length=64), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('tin', sa.String(length=20), nullable=False),
    sa.Column('period', sa.String(length=9), nullable=False),
    sa.Column('period_from', sa.Date(), nullable=True),
    sa.Column('period_to', sa.Date(), nullable=True),
    sa.Column('total_payment', sa.Float(), nullable=False),
    sa.Column('total_tax_deducted', sa.Float(), nullable=False),
    sa.Column('total_vds', sa.Float(), nullable=False),
    sa.Column('amount_in_words', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'GENERATED', 'SENT', 'VOID', name='certstatus'), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('pdf_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['tds_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_no'),
    sa.UniqueConstraint('tin', 'period', name='uq_cert_tin_period')
    )
    op.create_index(op.f('ix_tds_certificates_period'), 'tds_certificates', ['period'], unique=False)
    op.create_index(op.f('ix_tds_certificates_tin'), 'tds_certificates', ['tin'], unique=False)
    op.create_table('tds_import_row_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('column', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('raw_row', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['tds_import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tds_supplier_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('EMAIL', 'WHATSAPP', name='contactkind'), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['tds_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'kind', 'value')
    )
    op.create_table('tds_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('cheque_date', sa.Date(), nullable=True),
    sa.Column('cheque_number', sa.String(length=64), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('supplier_address', sa.Text(), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_no', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('depot_code', sa.String(length=64), nullable=True),
    sa.Column('description_of_payment', sa.String(length=255), nullable=True),
    sa.Column('sum_of_bill_amount', sa.Float(), nullable=True),
    sa.Column('sum_of_tds', sa.Float(), nullable=True),
    sa.Column('sum_of_vds', sa.Float(), nullable=True),
    sa.Column('match', sa.String(length=64), nullable=True),
    sa.Column('section', sa.String(length=32), nullable=True),
    sa.Column('tin', sa.String(length=20), nullable=True),
    sa.Column('challan_no', sa.String(length=64), nullable=True),
    sa.Column('challan_date', sa.Date(), nullable=True),
    sa.Column('cheque_challan_sl', sa.String(length=32), nullable=True),
    sa.Column('month', sa.String(length=32), nullable=True),
    sa.Column('total_challan_amount', sa.Float(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('fiscal_year', sa.String(length=9), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['tds_import_batches.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['tds_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tds_transactions_challan_no'), 'tds_transactions', ['challan_no'], unique=False)
    op.create_index(op.f('ix_tds_transactions_cheque_date'), 'tds_transactions', ['cheque_date'], unique=False)
    op.create_index(op.f('ix_tds_transactions_fiscal_year'), 'tds_transactions', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_tds_transactions_month'), 'tds_transactions', ['month'], unique=False)
    op.create_index(op.f('ix_tds_transactions_section'), 'tds_transactions', ['section'], unique=False)
    op.create_index(op.f('ix_tds_transactions_supplier_id'), 'tds_transactions', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_tds_transactions_tin'), 'tds_transactions', ['tin'], unique=False)
    op.create_table('tds_certificate_challan_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('sl', sa.Integer(), nullable=False),
    sa.Column('challan_number', sa.String(length=64), nullable=True),
    sa.Column('challan_date', sa.Date(), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('total_challan_amount', sa.Float(), nullable=True),
    sa.Column('amount_related', sa.Float(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['certificate_id'], ['tds_certificates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tds_certificate_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('sl', sa.Integer(), nullable=False),
    sa.Column('date_of_payment', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('section', sa.String(length=32), nullable=True),
    sa.Column('amount_of_payment', sa.Float(), nullable=True),
    sa.Column('amount_of_tax_deducted', sa.Float(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['certificate_id'], ['tds_certificates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tds_dispatch_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'WHATSAPP', name='dispatchchannel'), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SENDING', 'SENT', 'FAILED', name='dispatchstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['certificate_id'], ['tds_certificates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tds_override_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('anomalies', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('user', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['tds_certificates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tds_override_logs')
    op.drop_table('tds_dispatch_jobs')
    op.drop_table('tds_certificate_lines')
    op.drop_table('tds_certificate_challan_lines')
    op.drop_index(op.f('ix_tds_transactions_tin'), table_name='tds_transactions')
    op.drop_index(op.f('ix_tds_transactions_supplier_id'), table_name='tds_transactions')
    op.drop_index(op.f('ix_tds_transactions_section'), table_name='tds_transactions')
    op.drop_index(op.f('ix_tds_transactions_month'), table_name='tds_transactions')
    op.drop_index(op.f('ix_tds_transactions_fiscal_year'), table_name='tds_transactions')
    op.drop_index(op.f('ix_tds_transactions_cheque_date'), table_name='tds_transactions')
    op.drop_index(op.f('ix_tds_transactions_challan_no'), table_name='tds_transactions')
    op.drop_table('tds_transactions')
    op.drop_table('tds_supplier_contacts')
    op.drop_table('tds_import_row_errors')
    op.drop_index(op.f('ix_tds_certificates_tin'), table_name='tds_certificates')
    op.drop_index(op.f('ix_tds_certificates_period'), table_name='tds_certificates')
    op.drop_table('tds_certificates')
    op.drop_index(op.f('ix_tds_tax_rates_section'), table_name='tds_tax_rates')
    op.drop_table('tds_tax_rates')
    op.drop_index(op.f('ix_tds_suppliers_tin'), table_name='tds_suppliers')
    op.drop_index(op.f('ix_tds_suppliers_name'), table_name='tds_suppliers')
    op.drop_index(op.f('ix_tds_suppliers_bin'), table_name='tds_suppliers')
    op.drop_table('tds_suppliers')
    op.drop_table('tds_rate_anomalies')
    op.drop_table('tds_org_settings')
    op.drop_table('tds_numbering_config')
    op.drop_table('tds_number_sequences')
    op.drop_table('tds_import_batches')
    # ### end Alembic commands ###
